site_name: QPS-Infra

pages:
    - Overview: index.md
    - Getting Started: getting_started.md
    - FAQ: faq.md

theme:
  name: 'material'
repo_url: https://github.com/qaprosoft/qps-infra
repo_name: Github
