site_name: Zebrunner

pages:
    - Overview: index.md
    - Prerequisites: prerequisites.md
    - Installation Guide: install-guide.md
    - Configuration Guide: config-guide.md
    - User Guide: user-guide.md

theme:
  name: 'material'
repo_url: https://github.com/zebrunner/zebrunner
repo_name: Github
